# Generated by Django 5.2.8 on 2025-11-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
